services:
  postgres-zlagoda:
    image: postgres:latest
    container_name: postgres-zlagoda
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator-zlagoda:
    build: .
    container_name: migrator-zlagoda
    environment:
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres-zlagoda
      DB_PORT: 5432
      DB_DRIVER: ${DB_DRIVER}
    depends_on:
      postgres-zlagoda:
        condition: service_healthy
  api-zlagoda:
    build: .
    container_name: api-zlagoda
    ports:
      - "8080:8080"
    environment:
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres-zlagoda
      DB_PORT: 5432
      DB_DRIVER: ${DB_DRIVER}
      VAT_RATE: ${VAT_RATE:-0.2}
    depends_on:
      migrator-zlagoda:
        condition: service_completed_successfully
    entrypoint: ["./run.sh"]

volumes:
  postgres-data:
